version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    ports:
      - '3000:3000'
    volumes:
      - .:/src/app
      - /src/app/node_modules
